# training related
allow_variable_data_keys: true
seed: 2024
num_workers: 1
ngpu: 1
batch_type: numel
batch_bins: 400000
batch_size: 4
accum_grad: 1
max_epoch: 5
num_iters_per_epoch: 500
log_interval: 10
keep_nbest_models: 10
use_amp: false
multiple_iterator: false

optim: adamw
optim_conf:
    lr: 0.00001
    weight_decay: 0.000001
scheduler: steplr
scheduler_conf:
    step_size: 1
    gamma: 0.9

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 5